# @package _global_

# This config template will apply radial distortion transformation to all images 
# in the 'source' directory (supports nested directories)
# and save the distorted images in the 'destination' directory.

# It will apply the radial distortion with fixed lambda value
# hence it refers to the 'config.processor.FixedL'
# The lambda value controls the intensity level of the distortion.

# How to use it:
# 1. Set the path to the source images directory
# 2. Set the path to the destination directory.
# 3. Choose a radial disotrtion model:
# one of: division, perspective, stereographic, equisolid, orthogonal
# 4. Choose the lambda value. 
# Note: lambda should be negative for the division model.

defaults:
  - _self_

_target_: config.config.Config  # Python corresponding class
_convert_: object               # Used to convert nested _target_

run: transformation

transformation:
  _target_: config.transformation.Transformation
  source: "path/to/source/dataset"
  destination: "path/to/destination/dataset"
  transforms:
    '1':
      _target_: config.processor.FixedL
      transform: division
      l_value: -1.5

hydra:
  run:
    dir: outputs/${run}/${now:%Y-%m-%d}/${now:%H-%M-%S}
